# Sanity Check

Let's first check a couple packages we need in this class. Anaconda should have all the packages below (except for PyTorch) installed.

In [1]:
import torch
import scipy
import sklearn
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


Now let's check your Python version. Both 3.7 and 3.6 should work fine. If you have multiple Python environments installed, please pay attention to which one are you using. Nevertheless, we highly recommend using Anaconda to manager your packages.

In [2]:
!python --version

Python 3.6.9


# Orientation to Google Colab

Please note that Google Colab only has temporary storage. Once the current session disconnects (or timesout) all the files in the session storage will be discarded. However, the output from Jupyter Notebook will be saved unless you specify not to do so. You can download/upload files with the GUI in the left panel. If you would like to have a permanent storage (maybe for datasets and results), you can mount your Google Drive to Google Colab by running the cell below. You will be prompted to link your account to Colab. **The code in this section only works on Colab.**

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Run the cell below and you should see the changes in your Google Drive

In [4]:
with open('/content/drive/My Drive/boo.txt', 'w') as f:
  f.write('foo')

Don't forget to unmout at the end of your session.

In [5]:
drive.flush_and_unmount()

# Python Basics

Before diving into Python libraries, let's first take a look at Python's basic programming constructs.

## Basic Syntax

### Keywords

In [6]:
import keyword
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

### Identifiers


*   Identifiers in Python are case-sensitive.
*   The first character of any Python identifier can't be a digit. Other characters can be alphanumeric or an underscore. Non-ascii characters are also supported in Python 3.
*   !, @, #, $, and % are special symbols in Python and you can't use them as identifiers.





### Comments

In [7]:
# boo
'''
boo
foo
'''

"""
boo
foo
"""
print("Welcome to CS 361!")

Welcome to CS 361!


### Indentation
Python doesn't use `{}` for code blocks and is indentation-sensitive. This is America, you can whatever number of tabs/spaces you want for each code block, but the indentation level has to be the same within the same code block.

In [8]:
if True:
  print("True")
else:
  print("Truth always rests with the minority")

True


In [9]:
if True:
  print("True")
else:
  pass
print("False")

True
False


### Multi-line Expression

In [10]:
lets_make_this_line_super_super_super_super_super_super_super_super_super_long = 233
attempting_to_write_some_code_that_my_coworker_cant_maintain_so_that_i_could_keep_my_job = 666

We have to use backslash for a stand-alone multi-line expression.

In [11]:
lets_make_this_line_super_super_super_super_super_super_super_super_super_long + \
attempting_to_write_some_code_that_my_coworker_cant_maintain_so_that_i_could_keep_my_job

899

In [12]:
print(  
  lets_make_this_line_super_super_super_super_super_super_super_super_super_long +
  attempting_to_write_some_code_that_my_coworker_cant_maintain_so_that_i_could_keep_my_job   
)

899


In [13]:
[lets_make_this_line_super_super_super_super_super_super_super_super_super_long,
attempting_to_write_some_code_that_my_coworker_cant_maintain_so_that_i_could_keep_my_job]

[233, 666]

In [14]:
{lets_make_this_line_super_super_super_super_super_super_super_super_super_long,
attempting_to_write_some_code_that_my_coworker_cant_maintain_so_that_i_could_keep_my_job}

{233, 666}

## Data Types

### Built-in Numerical Data Types

* Integer

In [15]:
type(233)

int

* Float

In [16]:
type(233.666)

float

* Complex

In [17]:
type(233 + 666j)

complex

* Boolean: Be careful of compound boolean expression!

In [18]:
type(True)

bool

In [19]:
True and False

False

In [20]:
True or False

True

In [21]:
not True

False

*   Equality check

In [22]:
boo = [1, 2, 3]
foo = [1, 2, 3]
boo is foo # This is similar to boo == foo in Java

False

In [23]:
boo == foo # This is similar to boo.equals(foo) in Java

True

Note that Python doesn't have `===` like those in Kotlin and Javascript/TypeScript.

### String

*   `''` and `""` work the same for declaring string literals. If you use `""` to declare a string, you don't have to use escape character if you would like to use `''` as a part of the string literal.

In [24]:
"What's up?"

"What's up?"

In [25]:
'What\'s up?'

"What's up?"

*   Use `"""` or `'''` for multi-line strings

In [26]:
print(
  '''
  line 0
  line1
  '''
)


  line 0
  line1
  


*   String concatenation

In [27]:
"Welcome ""to ""CS 361"

'Welcome to CS 361'

In [28]:
"Welcome " + "to " + "CS 361"

'Welcome to CS 361'

*   String indexing: Python string can be index from left to right starting with 0 and right to left starting with -1

In [29]:
boo = "Welcome to CS 361!"

In [30]:
boo[0] # left to right

'W'

In [31]:
boo[-1] # right to left

'!'

*   String slicing [start:end:step]

In [32]:
boo[0:-1]

'Welcome to CS 361'

In [33]:
boo[0:7]

'Welcome'

In [34]:
boo[::2]

'Wloet S31'

In [35]:
boo[::-1]

'!163 SC ot emocleW'

In [36]:
boo[7::-1]

' emocleW'

In [37]:
boo[:7:-1]

'!163 SC ot'

In [38]:
boo[0:7:2]

'Wloe'

*   Byte-string: Please be aware of the existence of byte-string. If you have any byte-string imported into you dataset, please be careful when comparing string equality.

In [39]:
type(b'Hi!')

bytes

In [40]:
b'Hi!' == 'Hi!'

False

*   String Interpolation: C Style

In [41]:
"This is %s" % "CS 361!"

'This is CS 361!'

In [42]:
"Planck's constant is %e m^2 kg/s" % (6.62607004e-34)

"Planck's constant is 6.626070e-34 m^2 kg/s"

In [43]:
"Format a number into scientific notation: %e" % 233333

'Format a number into scientific notation: 2.333330e+05'

In [44]:
from math import pi
"π is approximately %f" % (pi)

'π is approximately 3.141593'

In [45]:
"π is approximately %.2f" % (pi)

'π is approximately 3.14'

*   String Interpolation: f-string

In [46]:
course = "CS 361"
f"Welcome to {course}"

'Welcome to CS 361'

In [47]:
f"1 + 1 = {1 + 1}"

'1 + 1 = 2'

*   String Interpolation: format function

In [48]:
"π is approximately {:.2f}".format(pi)

'π is approximately 3.14'

Checkout Python's [official document for string](https://docs.python.org/3.8/library/string.html) to see more details.

### List

*   List-indexing is very similar to string-indexing

In [49]:
boo = [0, 2, "four", 6, 8, "ten", 12, 14, 16, 18, 20]

In [50]:
boo[2]

'four'

In [51]:
boo[-1]

20

In [52]:
boo[-2]

18

In [53]:
boo[0:3]

[0, 2, 'four']

In [54]:
boo[::-2]

[20, 16, 12, 8, 'four', 0]

In [55]:
boo[-1:-6:-2]

[20, 16, 12]

*   Other List Tricks

In [56]:
"ten" in boo

True

In [57]:
boo.append("ha?")
boo

[0, 2, 'four', 6, 8, 'ten', 12, 14, 16, 18, 20, 'ha?']

In [58]:
boo.pop()

'ha?'

In [59]:
boo.remove("four")

In [60]:
len(boo)

10

Note that the two cells below repeat/concat two lists. However, it's a different story in Numpy.

In [61]:
[1, 2, 3] * 2

[1, 2, 3, 1, 2, 3]

In [62]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [63]:
foo = [[233, 666], [888, 999]]

In [64]:
foo[0][1]

666

*   List Comprehension: Save you some effort to write loops.

In [65]:
[x * 2 for x in boo]

[0, 4, 12, 16, 'tenten', 24, 28, 32, 36, 40]

In [66]:
[x ** 2 for x in boo if type(x) is int]

[0, 4, 36, 64, 144, 196, 256, 324, 400]

### Tuple

*   You can't modify a tuple once it's created.

In [67]:
foobar = ("boo", "foo")

*   [Destructuring assignment](https://blog.tecladocode.com/destructuring-in-python/)

In [68]:
(bar, baz) = foobar
bar

'boo'

In [69]:
baz

'foo'

### Set

*   Built-in functions

In [70]:
{1, 2, 3, "three", 4, 4, "five", "five"}

{1, 2, 3, 4, 'five', 'three'}

In [71]:
boo = {"a", "b", "b", "c"}
foo = {"a", "b", "b", "c"}

In [72]:
boo.add("d")
boo

{'a', 'b', 'c', 'd'}

In [73]:
"d" in boo

True

In [74]:
boo.union(foo)

{'a', 'b', 'c', 'd'}

In [75]:
boo.intersection(foo)

{'a', 'b', 'c'}

In [76]:
len(boo)

4

*   Set comprehension

In [77]:
{x * 2 for x in boo}

{'aa', 'bb', 'cc', 'dd'}

### Dictionary

In [78]:
grade_book = {"Alice": 90, "Bob": 93, "Charlie": 99, "Eve": 80}
grade_book

{'Alice': 90, 'Bob': 93, 'Charlie': 99, 'Eve': 80}

*  Loops

In [79]:
for name, grade in grade_book.items():
  print("Name: {:<7} | Grade: {:>4}".format(name, grade))

Name: Alice   | Grade:   90
Name: Bob     | Grade:   93
Name: Charlie | Grade:   99
Name: Eve     | Grade:   80


*   Dictionary Comprehension

In [80]:
{name: "A" if grade > 90 else "B" for name, grade in grade_book.items()}

{'Alice': 'B', 'Bob': 'A', 'Charlie': 'A', 'Eve': 'B'}

In [81]:
{x: x ** 2 for x in range(10) if x % 2 == 0}

{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}

## Functions: First-Class Citizens in Python

*   Declare a function

In [82]:
def square(x):
  return x ** 2

In [83]:
square_lambda = lambda x: x**2

* First-class citizen: It can be everywhere

In [84]:
def apply(f, x):
  return f(x)

apply(square, 2)

4

In [85]:
{x: square(x) for x in range(10) if x % 2 == 0}

{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}

*   Function Parameters

In [86]:
def greeting(name, loudness=0):
  return "HELLO, {}!!!".format(name.capitalize() * loudness) if loudness else "Hello, {}!".format(name)

In [87]:
greeting("Chenhui", 0)

'Hello, Chenhui!'

In [88]:
greeting("Chenhui")

'Hello, Chenhui!'

In [89]:
greeting("Chenhui", 10) # lol

'HELLO, ChenhuiChenhuiChenhuiChenhuiChenhuiChenhuiChenhuiChenhuiChenhuiChenhui!!!'

# NumPy Basics

## Terminology
> Credit to NumPy's [official document](https://numpy.org/doc/stable/glossary.html).

*   Rank: Number of dimensions.
*   Shape: A tuple to describe the size of each dimension.
*   View: An array that refers to another array’s data instead of a copy.
*   Slice: The selection of certain elements from a sequence.
*   Flatten: Collapsing a multi-dimensional arrary to a one-dimensional array.
*   Mask😷: A boolean array, used to select only certain elements for an operation.
*   Universal function: A fast element-wise, vectorized array operation. Examples include `add`, `sin` and `logical_or`.
*   Array-like: A sequence that can be interpreted as an ndarray, including nested lists, tuples, scalars and existing arrays.
*   Broadcast: The way how numpy treats arrays with different shapes, subject to certain constraints, during arithmetic operations.
*   Axis: Axes are defined for arrays with more than one dimension. A 2-dimensional array has two corresponding axes: the first running vertically downwards across rows (axis 0), and the second running horizontally across columns (axis 1). Many operations can take place along one of these axes
*   Vectorization: Optimizing a looping block by specialized code. NumPy uses vectorization to mean any optimization via specialized code performing the same operations on multiple elements, typically achieving speedups by avoiding some of the overhead in looking up and converting the elements. See the `Vectorization` section below for an very simple example.



## Ndarray


### Array Creation

A secret that I won't tell anyone: If you create a super big PyTorch tensor (on GPU) and do multiplication, Colab may temporarily upgrade your notebook environment (sometimes even with an V100 GPU). However, your session might get killed if you are unfortunate.

*   From Python array

In [90]:
np.array([233, 666, 999])

array([233, 666, 999])

In [91]:
np.array([[233, 666, 999], [233, 666, 999]])

array([[233, 666, 999],
       [233, 666, 999]])

*   Create constant arrays

In [92]:
np.zeros([100, 100, 100])

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [93]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [94]:
np.full((2, 3, 3), 5)

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

Of course you can also specify [NumPy datatypes](https://numpy.org/doc/stable/user/basics.types.html).

In [95]:
np.array([2, 3, 3], dtype=np.float32)

array([2., 3., 3.], dtype=float32)

Remeber the array-like sequence we mentioned above?

In [96]:
foo = [2, 3, 3] * 100
np.zeros_like(foo)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [97]:
boo = np.random.randint(-100, high=100, size=(10, 10))
np.ones_like(boo)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [98]:
np.eye(10) # identity matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

*  Would like to create a geometric/arithmetic sequence? Here you go.

In [99]:
np.arange(start=0, stop=101, step=2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [100]:
np.linspace(start=0., stop=100., num=51, retstep=True)

(array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
         22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,
         44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,
         66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,
         88.,  90.,  92.,  94.,  96.,  98., 100.]), 2.0)

In [101]:
np.logspace(start=1, stop=5, num=5, base=2)

array([ 2.,  4.,  8., 16., 32.])

### Array Properties

In [102]:
boo.size

100

In [103]:
boo.shape

(10, 10)

In [104]:
boo.dtype

dtype('int64')

### Array Reshape
![](https://forum.onefourthlabs.com/uploads/default/original/2X/d/dc52bf0fac7ecdf30c66cfd4625ccf58e74fba02.jpeg)

In [105]:
boo = np.linspace(start=1., stop=99., num=50)

In [106]:
bar = boo.reshape((10, 5))
bar

array([[ 1.,  3.,  5.,  7.,  9.],
       [11., 13., 15., 17., 19.],
       [21., 23., 25., 27., 29.],
       [31., 33., 35., 37., 39.],
       [41., 43., 45., 47., 49.],
       [51., 53., 55., 57., 59.],
       [61., 63., 65., 67., 69.],
       [71., 73., 75., 77., 79.],
       [81., 83., 85., 87., 89.],
       [91., 93., 95., 97., 99.]])

In [107]:
bar.T
bar.transpose()

array([[ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.],
       [ 3., 13., 23., 33., 43., 53., 63., 73., 83., 93.],
       [ 5., 15., 25., 35., 45., 55., 65., 75., 85., 95.],
       [ 7., 17., 27., 37., 47., 57., 67., 77., 87., 97.],
       [ 9., 19., 29., 39., 49., 59., 69., 79., 89., 99.]])

In [108]:
foo = np.array([[1, 2, 3]])
foo

array([[1, 2, 3]])

We can also specify the size of one dimension as `-1` (unknown) during reshaping. This will let NumPy figure out the size of that dimenion.

In [109]:
foo.reshape(-1)

array([1, 2, 3])

In [110]:
np.ones((1, 2, 3)).flatten()

array([1., 1., 1., 1., 1., 1.])

### Indexing and Slicing
*   Similar story like what what we did for Python arrays but with extra toppings.

In [111]:
boo = np.random.randn(225, 233, 361)
boo.shape

(225, 233, 361)

In [112]:
boo[:, :, :].shape # I want them all!

(225, 233, 361)

In [113]:
boo[0:-10:2, :, ...].shape # Too lazy to specify the size of one dimension to be sliced

(108, 233, 361)

In [114]:
boo[::-1, 1, 1].shape

(225,)

*   Fancy indexing (Yeah that's what people call it😂) with boolean mask: Note that boolean mask indexing creates a new ndarray instead of a view.

In [115]:
foo = np.random.randn(100)
foo[foo > 0]

array([2.12701473, 0.63942834, 0.22718926, 0.52993651, 0.89701161,
       0.82117775, 1.20530214, 0.71777746, 0.70271826, 1.51285803,
       0.29674284, 0.70284139, 0.22882979, 2.55674239, 0.57116652,
       0.68257584, 0.50722031, 0.76211708, 0.57494169, 0.79255371,
       1.24888357, 0.43719552, 1.67405558, 1.52888972, 0.9072276 ,
       1.04638198, 0.88427903, 1.43794226, 0.21611371, 0.07669479,
       0.80575738, 0.08277253, 0.84167283, 0.52256416, 0.01943359,
       1.21073489, 1.30004129, 0.11335488, 0.5829766 , 0.95906999,
       1.33226717, 0.12803408, 0.82453801, 0.88587082, 1.91165186,
       1.31365509, 1.18027224, 1.4672934 , 0.37037176, 1.31047233,
       0.93349867, 0.95674321, 0.010709  ])

In [116]:
boo[boo < 0]

array([-0.52892378, -0.56789592, -0.21545509, ..., -0.14672712,
       -0.81753917, -0.44295658])

*   Fancy indexing with integer array: Note that integer array indexing creates a new ndarray instead of a view.

In [117]:
foo = np.random.randint(0, 100, (10, 10))
foo

array([[96, 91, 70, 78, 37, 94,  2,  1, 66, 80],
       [ 8, 26, 82, 92, 90, 88,  4, 21,  3, 22],
       [64, 48, 76, 66, 55, 40, 33, 56, 78, 21],
       [98, 98, 20, 39,  1, 29, 59, 28, 88, 14],
       [68, 30, 76, 71, 56, 52, 10, 50, 33, 97],
       [56, 38,  9,  4, 33, 73, 51, 72,  1, 65],
       [56, 41, 77, 65,  2, 11, 84, 46, 37,  9],
       [39, 95, 68, 52, 62, 21, 78, 10, 54, 15],
       [63, 63, 27, 55, 51, 52, 13, 78, 94, 82],
       [76, 25, 49, 70, 43,  8, 63,  0, 28, 69]])

In [118]:
foo[[1, 2, 3], [1, 2, 3]] # Basically we are picking out numbers with position (1, 1), (2, 2), and (3, 3)

array([26, 76, 39])

Same story for high-dimensional array.

In [119]:
bar = np.random.randint(0, 100, (10, 10, 10))
bar[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

array([ 5, 59, 16])

We can even mix slicing with indexing.

In [120]:
foo[3:7, [0, 1, 2, 3]]

array([[98, 98, 20, 39],
       [68, 30, 76, 71],
       [56, 38,  9,  4],
       [56, 41, 77, 65]])

## NumPy Math/Statistics

### Random Numbers

In [121]:
np.random.seed(0)

In [122]:
np.random.randn(10, 10)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
        -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
         0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502,  2.26975462,
        -1.45436567,  0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647, -0.34791215,
         0.15634897,  1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 , -0.50965218,
        -0.4380743 , -1.25279536,  0.77749036, -1.61389785, -0.21274028],
       [-0.89546656,  0.3869025 , -0.51080514, -1.18063218, -0.02818223,
         0.42833187,  0.06651722,  0.3024719 , -0.63432209, -0.36274117],
       [-0.67246045, -0.35955316, -0.81314628, -1.7262826 ,  0.17742614,
        -0.40178094, -1.63019835,  0.46278226

In [123]:
np.random.uniform(low=0, high=1, size=10)

array([0.42385505, 0.60639321, 0.0191932 , 0.30157482, 0.66017354,
       0.29007761, 0.61801543, 0.4287687 , 0.13547406, 0.29828233])

In [124]:
np.random.binomial(n=10, p=0.1, size=10)

array([1, 1, 1, 1, 1, 1, 2, 1, 1, 2])

In [125]:
np.random.randint(low=-10, high=10, size=10)

array([ -5,   1, -10,   1,  -2,   0,   1,  -5,   5,  -2])

In [126]:
np.random.choice([1, 2, 3, 4], size=5, replace=True)

array([3, 4, 4, 2, 4])

In [127]:
np.random.choice([1, 2, 3, 4], size=5, replace=True, p=[0.2, 0.3, 0.2, 0.3])

array([4, 4, 2, 1, 1])

See the official documentation for more examples.

### Statistics

In [128]:
boo = np.random.randn(3, 5)
boo

array([[-2.34795257e-02,  8.94222897e-02, -5.94327371e-01,
        -1.05696794e-01,  7.42795713e-01],
       [-7.54981527e-01, -1.38282715e-01, -2.12492027e+00,
        -1.03001883e+00, -5.17451865e-01],
       [-1.41800012e-01, -1.27648021e+00,  1.48151328e+00,
         1.65927664e+00,  1.39611962e-04]])

In [129]:
boo.std() == boo.flatten().std() # Yes, my mon told me not to compare float numbers this way, but the point here is that std() by default flattens the array.

True

In [130]:
boo.std(axis=0) # std of each column (along the rows)

array([0.32060472, 0.59749782, 1.47791865, 1.11563697, 0.51722153])

In [131]:
boo.std(axis=1) # std of each row (along the columns)

array([0.42949416, 0.67291294, 1.095818  ])

Watch out for the degree of freedom (depending whether you are running population std or sample std and your downstream task). Prof. Liu will talk about degree of freedom later in the course.

In [132]:
boo.std(ddof=0)

0.9471697038935211

In [133]:
boo.mean()

-0.1822861061868246

In [134]:
boo.sum()

-2.7342915928023688

### Element-wise Operations

In [135]:
boo = np.arange(0, 20).reshape((4, 5))
boo

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [136]:
foo = np.arange(0, 5)
foo

array([0, 1, 2, 3, 4])

In [137]:
foo ** 2

array([ 0,  1,  4,  9, 16])

In [138]:
foo - 1

array([-1,  0,  1,  2,  3])

In [139]:
foo - np.arange(-5, 0)

array([5, 5, 5, 5, 5])

In [140]:
boo * foo

array([[ 0,  1,  4,  9, 16],
       [ 0,  6, 14, 24, 36],
       [ 0, 11, 24, 39, 56],
       [ 0, 16, 34, 54, 76]])

Wait... What? **PLEASE NOTE THAT THE CODE ABOVE IS NOT DOING MATRIX MULTIPLICATIONS.** ~Serious side effect may include but not limited to... (OK..OK.. I can't make this tutorial a TV prescription drug ad.)~ The code in the cell below is how you do a matrix multiplication.

In [141]:
boo @ foo

array([ 30,  80, 130, 180])

But what happened when we did `boo * foo`? This is our next fairy tale.

## Broadcast

Let's say I'd like to subtract a constant from a very large ndarray `boo`. Without broadcasting, I have to create an array with the same size as `boo`. However, this is not very efficient. This is the basic idea of broadcast: making arithmetic operations happen when two arrays even have incompatible shapes. For the `boo * foo` example above, we "copy" `foo` for five times and make its shape compatible with `boo`. 

~The COVID testing took my entire morning away so I'll just copy the official documentation. (Sorry, that's not an excuse.)~

![Meme](https://imgs.xkcd.com/comics/compiling.png)\
Wait... Python does not compile... Nevermind...

The rules for broadcasting go as below ([credit](https://cs231n.github.io/python-numpy-tutorial/#broadcasting)):
*   If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
*   The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
*   The arrays can be broadcast together if they are compatible in all dimensions.
*   After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
*   In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

Checkout [this link](https://numpy.org/devdocs/user/theory.broadcasting.html) for the motivation behind this design and the related rules. Below are some examples.

![Boradcast 1](https://numpy.org/doc/stable/_images/theory.broadcast_1.gif)\
![Broadcast 2](https://numpy.org/doc/stable/_images/theory.broadcast_2.gif)\
![Broadcast 3](https://numpy.org/doc/stable/_images/theory.broadcast_3.gif)\
When the trailing dimensions of the arrays are unequal, broadcasting fails because it is impossible to align the values in the rows of the 1st array with the elements of the 2nd arrays for element-by-element addition.



## Vectorization

The basic idea of doing vectorization with NumPy is to converting vanilla loops into ndarray-based NumPy operations without explicit looping. We usually (at least for simple problems) generate all the random trials onece and then accumulate the result with highly-optimized NumPy functions. We won't get into too much detail but below is a naive example.

In [142]:
%%timeit
from random import randint
path = []
pos = 0
for i in range(int(1e5)):
  walk = randint(-100, 100)
  path.append(pos)
  pos += walk

10 loops, best of 3: 120 ms per loop


In [143]:
%%timeit
walks = np.random.randint(-100, high=100, size=int(1e5))
path = np.cumsum(walks)

1000 loops, best of 3: 1.45 ms per loop


See the difference? Vectorization could save you a huge amount of time on a later homework about simulation (and in a whole bunch of other sceanrios). Side Note: Packages like `Numba` could also bring vectorization and JIT compilation to CPython. However, please do watch out for any unintended behaviors when using such packages. (I recommended `Numba` to a friend who is doing a research project and it messed up his experiment results...🤦)

In [144]:
from numba import jit
@jit(nopython=True)
def random_walk(steps):
  path = []
  pos = 0
  for i in range(int(steps)):
    walk = np.random.randint(-100, high=100)
    path.append(pos)
    pos += walk
  return path

In [145]:
%%timeit
random_walk(1e5) # Not bad!

The slowest run took 29.31 times longer than the fastest. This could mean that an intermediate result is being cached.
100 loops, best of 3: 6.43 ms per loop


![Meme](https://i.redd.it/nklty63uzav41.png)

# Other Libraries by Examples
*  [Notebook1](https://colab.research.google.com/github/danielz02/CS361_Notebook_Collection/blob/master/Notebook1_Pandas_Histogram.ipynb): Matplotlib and Pandas
*  [Notebook2](https://github.com/danielz02/CS361_Notebook_Collection/blob/master/Notebook2_Time_Series_Boxplot_Corr.ipynb): Matplotlib and Pandas (Cont.d)
*  [Notebook3](https://colab.research.google.com/github/danielz02/CS361_Notebook_Collection/blob/master/Notebook3_Scatter_Corr.ipynb): Correlation Coefficient
*  [Notebook4](https://colab.research.google.com/github/danielz02/CS361_Notebook_Collection/blob/master/Notebook4_Simulation.ipynb): Simulation
*  [Notebook5](https://colab.research.google.com/github/danielz02/CS361_Notebook_Collection/blob/master/Notebook5_Covariance_PCA.ipynb): PCA
*  [Notebook6](https://colab.research.google.com/github/danielz02/CS361_Notebook_Collection/blob/master/Notebook6_PCA.ipynb): PCA (Cont.d)

# Reference
*   [What's NumPy](https://numpy.org/doc/stable/user/whatisnumpy.html)
*   [NumPy Indexing](https://numpy.org/doc/stable/user/basics.indexing.html)
*   [NumPy Glossary](https://numpy.org/doc/stable/glossary.html)
*   [Stanford CS 231n](https://cs231n.github.io/python-numpy-tutorial/)
*   [NumPy Cheatsheet](https://www.dataquest.io/blog/numpy-cheat-sheet/)
*   [NumPy Broadcasting](https://numpy.org/doc/stable/user/theory.broadcasting.html)
*   [Meme from Unknown Source](https://forum.onefourthlabs.com/t/numpy-reshaping/5813)